version: '3'

services:

  postgres:
    image: 'postgres:11.1-alpine'
    volumes:
      - '../volumes/postgres11:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=development

  rabbit:
    image: 'rabbitmq:3.7-management-alpine'
    hostname: 'rabbit'
    volumes:
      - '../volumes/rabbitmq:/var/lib/rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
